2025-07-07 23:47:54,337 INFO    MainThread:4091914 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-07-07 23:47:54,337 INFO    MainThread:4091914 [wandb_setup.py:_flush():67] Configure stats pid to 4091914
2025-07-07 23:47:54,337 INFO    MainThread:4091914 [wandb_setup.py:_flush():67] Loading settings from /home/aavash/.config/wandb/settings
2025-07-07 23:47:54,337 INFO    MainThread:4091914 [wandb_setup.py:_flush():67] Loading settings from /mnt/Enterprise3/aavash/sagar/classification/src/experiments/wandb/settings
2025-07-07 23:47:54,337 INFO    MainThread:4091914 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-07-07 23:47:54,337 INFO    MainThread:4091914 [wandb_init.py:setup_run_log_directory():647] Logging user logs to ./wandb/run-20250707_234754-enz9vhdf/logs/debug.log
2025-07-07 23:47:54,337 INFO    MainThread:4091914 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to ./wandb/run-20250707_234754-enz9vhdf/logs/debug-internal.log
2025-07-07 23:47:54,337 INFO    MainThread:4091914 [wandb_init.py:init():761] calling init triggers
2025-07-07 23:47:54,337 INFO    MainThread:4091914 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-07-07 23:47:54,337 INFO    MainThread:4091914 [wandb_init.py:init():784] starting backend
2025-07-07 23:47:54,337 INFO    MainThread:4091914 [wandb_init.py:init():788] sending inform_init request
2025-07-07 23:47:54,342 INFO    MainThread:4091914 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-07-07 23:47:54,342 INFO    MainThread:4091914 [wandb_init.py:init():798] backend started and connected
2025-07-07 23:47:54,343 INFO    MainThread:4091914 [wandb_init.py:init():891] updated telemetry
2025-07-07 23:47:54,344 INFO    MainThread:4091914 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-07-07 23:47:55,473 INFO    MainThread:4091914 [wandb_init.py:init():990] starting run threads in backend
2025-07-07 23:47:55,750 INFO    MainThread:4091914 [wandb_run.py:_console_start():2375] atexit reg
2025-07-07 23:47:55,750 INFO    MainThread:4091914 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-07-07 23:47:55,750 INFO    MainThread:4091914 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-07-07 23:47:55,751 INFO    MainThread:4091914 [wandb_run.py:_redirect():2315] Redirects installed.
2025-07-07 23:47:55,753 INFO    MainThread:4091914 [wandb_init.py:init():1032] run started, returning control to user process
2025-07-07 23:47:55,753 INFO    MainThread:4091914 [wandb_run.py:_config_callback():1261] config_cb None None {'batch_size': 32, 'learning_rate': 0.001, 'weight_decay': 0.005, 'lr_decay': 0.995, 'num_classes': 9, 'augmentation': 'transform_1()', 'model': 'ProvGigaPath'}
2025-07-08 08:23:38,769 INFO    MsgRouterThr:4091914 [mailbox.py:close():129] Closing mailbox, abandoning 1 handles.
2025-07-08 08:23:41,067 ERROR   MainThread:4091914 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-08 08:23:41,070 ERROR   MainThread:4091914 [redirect.py:_on_write():661] error in stdout callback
Traceback (most recent call last):
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2296, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 401, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1444, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/aavash/.local/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
